# ConsolidateData.R -              -*-R-*-
#  Write out final data table, with climate data in 3-month seasons
#  Author:  Tom Wainwright, thomas.wainwright@noaa.gov
#  Created:  28 Jan 2014
#

## This script takes data tables generated by ProcessData.R and writes out
## the final complete data table used by the analysis.

# Column names for the output file

seasonNames <-c('JFM', 'AMJ', 'JAS', 'OND')

.colnames <- c('YEAR', 
               paste('PDO_', seasonNames, sep=''), 
               paste('ONI_', seasonNames, sep=''), 
               paste('UWI_', seasonNames, sep=''), 
               paste('SST_', seasonNames, sep=''), 
               paste('NPGO_', seasonNames, sep=''), 
               'SPR.TRN')
print(.colnames)
.nseries <- length(.colnames)
cat('\nNumber of series: ', .nseries, '\n')

# The data table extends from 1950 to the current year:
.yrs <- 1950:as.numeric(format(Sys.time(), '%Y'))
.nyrs <- length(.yrs)
cat('\nNumber of years: ', .nyrs, '\n')

seasAve <- function(montbl) {
  # A function to generate the 3-mo seasonal averages from
  # standard format monthly data tables (montbl) with Year in column 1
  # followed by monthly data in columns 2:13.
  
  # First, copy the data to a table from 1950 to the current year:
  .mtab <- matrix(NA, nrow=length(.yrs), ncol=12,
                  dimnames=list(.yrs, month.abb))
  #  Following assumes montbl is complete and in order by years:
##print(as.vector(montbl[ , 'Year']))
  .mtab[.yrs %in% montbl[ , 'Year'], ] <-
    as.matrix(montbl)[montbl[ , 'Year'] %in% .yrs, 2:13]
##print(.mtab)
  combineCols <- list(month.abb[1:3], month.abb[4:6], month.abb[7:9], month.abb[10:12])
  .res <- data.frame(lapply(combineCols,
                            function(x) {apply(.mtab[,x], 1, mean, na.rm=TRUE)}))
  dimnames(.res) <- list(.yrs, seasonNames)
##.res[is.nan(.res)] <- NA
  return(round(.res, 3))
} # end seasAve()


# Create the result matrix:
phys3mo <- as.data.frame(matrix(NA, ncol=.nseries, nrow=.nyrs,
                  dimnames=list(.yrs, .colnames)))
print(str(phys3mo))

# Process the variables in order:

#   YEAR
phys3mo[ , 'YEAR'] <- .yrs
print(str(phys3mo))

#   PDO
.cols <- grep('PDO_', .colnames)
print(.cols)
.dat <- seasAve(PDO.mon)
print(str(.dat))
phys3mo[ , .cols] <- .dat

#   ONI
.names <- paste('ONI_', seasonNames, sep='')
.dat <- seasAve(ONI.mon)
phys3mo[ , .names] <- .dat

#   UWI
.names <- paste('UWI_', seasonNames, sep='')
.dat <- seasAve(UWI.mon)
phys3mo[ , .names] <- .dat

#   SST
.names <- paste('SST_', seasonNames, sep='')
.dat <- seasAve(CWT.mon)  #NOTE: data series name differs
phys3mo[ , .names] <- .dat

#   NPGO
.names <- paste('NPGO_', seasonNames, sep='')
.dat <- seasAve(NPGO.mon)
phys3mo[ , .names] <- .dat

#  SPR.TRN - Annual Series
##print(summary(SPT.LGR.ann))
phys3mo[.yrs %in% SPT.LGR.ann$DecYr , 'SPR.TRN'] <-
  SPT.LGR.ann$Data[SPT.LGR.ann$DecYr %in% .yrs]

write.csv(phys3mo, file.path(d.dir, 'AnalysisData.csv'),
            row.names=FALSE)
