# ConsolidateData.R -              -*-R-*-
#  Write out final data table, with climate data in 3-month seasons
#  Author:  Tom Wainwright, thomas.wainwright@noaa.gov
#  Created:  28 Jan 2014
#

## This script takes data tables generated by ProcessData.R and writes out
## the final complete data table used by the analysis.

# Column names for the output file

seasonNames <-c('JFM', 'AMJ', 'JAS', 'OND')

.colnames <- c('YEAR', 'OCN.RCR', 'OCN.SPN',
               paste('PDO.', seasonNames, sep=''), 
               paste('ONI.', seasonNames, sep=''), 
               paste('UWI.', seasonNames, sep=''), 
               paste('SST.', seasonNames, sep=''), 
               paste('NPGO.', seasonNames, sep=''), 
               'SPT.LGR', 'SPT.BIO', 'COP.RCH', 'COP.NAN', 'COP.SAN', 
               'TMP.DP', 'SAL.DP', 'ICH.BIO', 'ICH.COM')
# print(.colnames)  ### DEBUG ###
.nseries <- length(.colnames)
cat('\nNumber of series: ', .nseries, '\n')

# The data table extends from 1950 to the current year:
.yrs <- 1950:as.numeric(format(Sys.time(), '%Y'))
.nyrs <- length(.yrs)
cat('\nNumber of years: ', .nyrs, '\n')

seasAve <- function(montbl) {
  # A function to generate the 3-mo seasonal averages from
  # standard format monthly data tables (montbl) with Year in column 1
  # followed by monthly data in columns 2:13.
  
  # First, copy the data to a table from 1950 to the current year:
  .mtab <- matrix(NA, nrow=length(.yrs), ncol=12,
                  dimnames=list(.yrs, month.abb))
  #  Following assumes montbl is complete and in order by years:
##print(as.vector(montbl[ , 'Year']))
  .mtab[.yrs %in% montbl[ , 'Year'], ] <-
    as.matrix(montbl)[montbl[ , 'Year'] %in% .yrs, 2:13]
##print(.mtab)
  combineCols <- list(month.abb[1:3], month.abb[4:6], month.abb[7:9], month.abb[10:12])
  .res <- data.frame(lapply(combineCols,
                            function(x) {apply(.mtab[,x], 1, mean, na.rm=TRUE)}))
  dimnames(.res) <- list(.yrs, seasonNames)
##.res[is.nan(.res)] <- NA
  return(round(.res, 3))
} # end seasAve()


# Create the result matrix:
phys3mo <- as.data.frame(matrix(NA, ncol=.nseries, nrow=.nyrs,
                  dimnames=list(.yrs, .colnames)))
# print(str(phys3mo))  ### DEBUG ###

# Process the variables in order:

#   YEAR
phys3mo[ , 'YEAR'] <- .yrs
# print(str(phys3mo))  ### DEBUG ###

#  OCN.RCR - Annual Series
phys3mo[.yrs %in% OCN.RCR.ann$DecYr , 'OCN.RCR'] <-
  OCN.RCR.ann$Data[OCN.RCR.ann$DecYr %in% .yrs]

#  OCN.SPN - Annual Series
phys3mo[.yrs %in% OCN.SPN.ann$DecYr , 'OCN.SPN'] <-
  OCN.SPN.ann$Data[OCN.SPN.ann$DecYr %in% .yrs]

#   PDO
.cols <- grep('PDO.', .colnames)
.dat <- seasAve(PDO.mon)
# print(str(.dat))  ### DEBUG ###
phys3mo[ , .cols] <- .dat

#   ONI
.names <- paste('ONI.', seasonNames, sep='')
.dat <- seasAve(ONI.mon)
phys3mo[ , .names] <- .dat

#   UWI
.names <- paste('UWI.', seasonNames, sep='')
.dat <- seasAve(UWI.mon)
phys3mo[ , .names] <- .dat

#   SST
.names <- paste('SST.', seasonNames, sep='')
.dat <- seasAve(CWT.mon)  #NOTE: data series name differs
phys3mo[ , .names] <- .dat

#   NPGO
.names <- paste('NPGO.', seasonNames, sep='')
.dat <- seasAve(NPGO.mon)
phys3mo[ , .names] <- .dat

#  SPT.LGR - Annual Series
phys3mo[.yrs %in% SPT.LGR.ann$DecYr , 'SPT.LGR'] <-
  SPT.LGR.ann$Data[SPT.LGR.ann$DecYr %in% .yrs]

# SPT.BIO - Annual Series
phys3mo[.yrs %in% SPT.BIO.ann$DecYr , 'SPT.BIO'] <-
  SPT.BIO.ann$Data[SPT.BIO.ann$DecYr %in% .yrs]

# 'COP.RCH'
# COP.RCH - Annual Series
phys3mo[.yrs %in% COP.RCH.ann$DecYr , 'COP.RCH'] <-
  COP.RCH.ann$Data[COP.RCH.ann$DecYr %in% .yrs]

# 'COP.NAN'
# COP.NAN - Annual Series
phys3mo[.yrs %in% COP.NAN.ann$DecYr , 'COP.NAN'] <-
  COP.NAN.ann$Data[COP.NAN.ann$DecYr %in% .yrs]

# 'COP.SAN'
# COP.SAN - Annual Series
phys3mo[.yrs %in% COP.SAN.ann$DecYr , 'COP.SAN'] <-
  COP.SAN.ann$Data[COP.SAN.ann$DecYr %in% .yrs]

# 'TMP.DP'
# TMP.DP - Annual Series
phys3mo[.yrs %in% TMP.DP.ann$DecYr , 'TMP.DP'] <-
  TMP.DP.ann$Data[TMP.DP.ann$DecYr %in% .yrs]

# 'SAL.DP'
# SAL.DP - Annual Series
phys3mo[.yrs %in% SAL.DP.ann$DecYr , 'SAL.DP'] <-
  SAL.DP.ann$Data[SAL.DP.ann$DecYr %in% .yrs]

# 'ICH.BIO'
# ICH.BIO - Annual Series
phys3mo[.yrs %in% ICH.BIO.ann$DecYr , 'ICH.BIO'] <-
  ICH.BIO.ann$Data[ICH.BIO.ann$DecYr %in% .yrs]

# 'ICH.COM'
# ICH.COM - Annual Series
phys3mo[.yrs %in% ICH.COM.ann$DecYr , 'ICH.COM'] <-
  ICH.COM.ann$Data[ICH.COM.ann$DecYr %in% .yrs]

## WRITE OUT FINAL ANALYSIS DATA TABLE:

write.csv(phys3mo, file.path(d.dir, 'AnalysisData.csv'),
            row.names=FALSE)
