# WritePhysical3mo.R -              -*-R-*-
#  Write out physics data for OCNR_Model_3var analysis
#  Author:  Tom Wainwright, thomas.wainwright@noaa.gov
#  Created:  28 Jan 2014
#

## This script takes data tables generated by ProcessData.R and writes out
## the Physical_3mo.dat file used by the OCNR_Model_3var.

# Column names for the output file (must match code in OCNR_Model_3var.R)

.colnames <- c('YEAR', 'PDO_DJF', 'PDO_JFM', 'PDO_FMA', 'PDO_MAM', 'PDO_AMJ', 'PDO_MJJ', 
               'PDO_JJA', 'PDO_JAS', 'PDO_ASO', 'PDO_SON', 'PDO_OND', 'PDO_NDJ', 'PDO_D', 'PDO_J', 
               'ONI_DJF', 'ONI_JFM', 'ONI_FMA', 'ONI_MAM', 'ONI_AMJ', 'ONI_MJJ', 
               'ONI_JJA', 'ONI_JAS', 'ONI_ASO', 'ONI_SON', 'ONI_OND', 'ONI_NDJ', 'ONI_D', 'ONI_J', 
               'UWI_DJF', 'UWI_JFM', 'UWI_FMA', 'UWI_MAM', 'UWI_AMJ', 'UWI_MJJ', 
               'UWI_JJA', 'UWI_JAS', 'UWI_ASO', 'UWI_SON', 'UWI_OND', 'UWI_NDJ', 'UWI_D', 'UWI_J', 
               # 'BFL_DJF', 'BFL_JFM', 'BFL_FMA', 'BFL_MAM', 'BFL_AMJ', 'BFL_MJJ', 
               # 'BFL_JJA', 'BFL_JAS', 'BFL_ASO', 'BFL_SON', 'BFL_OND', 'BFL_NDJ', 'BFL_D', 'BFL_J', 
               # 'SLH_DJF', 'SLH_JFM', 'SLH_FMA', 'SLH_MAM', 'SLH_AMJ', 'SLH_MJJ', 
               # 'SLH_JJA', 'SLH_JAS', 'SLH_ASO', 'SLH_SON', 'SLH_OND', 'SLH_NDJ', 'SLH_D', 'SLH_J', 
               'SST_DJF', 'SST_JFM', 'SST_FMA', 'SST_MAM', 'SST_AMJ', 'SST_MJJ', 
               'SST_JJA', 'SST_JAS', 'SST_ASO', 'SST_SON', 'SST_OND', 'SST_NDJ', 'SST_D', 'SST_J', 
               # 'NPI_DJF', 'NPI_JFM', 'NPI_FMA', 'NPI_MAM', 'NPI_AMJ', 'NPI_MJJ', 
               # 'NPI_JJA', 'NPI_JAS', 'NPI_ASO', 'NPI_SON', 'NPI_OND', 'NPI_NDJ', 'NPI_D', 'NPI_J', 
               # 'MEI_DJ', 'MEI_JF', 'MEI_FM', 'MEI_MA', 'MEI_AM', 'MEI_MJ', 
               # 'MEI_JJ', 'MEI_JA', 'MEI_AS', 'MEI_SO', 'MEI_ON', 'MEI_ND', 'MEI_ND.1', 'MEI_DJ.1', 
               'NPGO_DJF', 'NPGO_JFM', 'NPGO_FMA', 'NPGO_MAM', 'NPGO_AMJ', 'NPGO_MJJ', 
               'NPGO_JJA', 'NPGO_JAS', 'NPGO_ASO', 'NPGO_SON', 'NPGO_OND', 'NPGO_NDJ', 'NPGO_D', 'NPGO_J', 
               'SPR.TRN')
.nseries <- length(.colnames)
cat('\nNumber of series: ', .nseries, '\n')

# Most of these variables are not actually used in the model, and are there
# for historical reasons. Unfortunately, the OCNR_Model_3var code uses
# numeric column indices rather than variable names to access the data, so
# the columns must line-up exactly with that code, regardless of their names.

# The data table extends from 1950 to the current year:
.yrs <- 1950:as.numeric(format(Sys.time(), '%Y'))
.nyrs <- length(.yrs)
cat('\nNumber of years: ', .nyrs, '\n')

# There are 10 data series used:
#   PDO, ONI, UWI, BFL, SLH, SST, NPI, MEI, NPGO, and SPR.TRN
# All but MEI and SPR.TRN are converted to 3-month moving averages
# MEI is converted to a 2-month MA, and SPR.TRN is an annual variable.

# For the 3-mo MA variables, the pattern is:
#  12 3-mo MAs centered on the months Jan - Dec of each year, plus single
#  month values for Dec of the year and Jan of the next year.

ma3Names <-c('DJF', 'JFM', 'FMA', 'MAM', 'AMJ', 'MJJ',
             'JJA', 'JAS', 'ASO', 'SON', 'OND', 'NDJ', 'D', 'J')

threeMoMA <- function(montbl) {
  # A function to generate the standard 3-mo MA + 2 variable tables from
  # standard format monthly data tables (montbl) with Year in column 1
  # followed by monthly data in columns 2:13.
  
  # First, copy the data to a table from 1950 to the current year:
  .mtab <- matrix(NA, nrow=length(.yrs), ncol=12,
                  dimnames=list(.yrs, month.abb))
  #  Following assumes montbl is complete and in order by years:
##print(as.vector(montbl[ , 'Year']))
  .mtab[.yrs %in% montbl[ , 'Year'], ] <-
    as.matrix(montbl)[montbl[ , 'Year'] %in% .yrs, 2:13]
##print(.mtab)
  # Second, create a 3-page array with data tables lagged -1, 0, +1 months
  .lagtab <- array(NA, dim=c(dim(.mtab), 3))
##print(dim(.lagtab))
  #  lag -1 months, Dec(y-1) - Nov(y)
  .lagtab[ , , 1] <- cbind(c(NA, .mtab[1:(.nyrs-1), 12]), .mtab[ , 1:11])
  #  lag 0 months
  .lagtab[ , , 2] <- .mtab
  #  lag +1 months, (Feb(y) - Jan(y+1)
  .lagtab[ , , 3] <- cbind(.mtab[ , 2:12], c(.mtab[2:.nyrs, 1], NA))
##print(.lagtab[1:10, , ])
  # compute moving averate
  .res <- apply(.lagtab, c(1,2), mean, na.rm=T)
  # add on Dec(Y) and Jan(Y+1) data:
  .res <- cbind(.res, .lagtab[ , 12, 2], .lagtab[ , 12, 3]) 
  dimnames(.res) <- list(.yrs, ma3Names)
  .res[is.nan(.res)] <- NA
  return(round(.res, 3))
} # end threeMoMA()


# Create the result matrix:
phys3mo <- matrix(NA, ncol=.nseries, nrow=.nyrs,
                  dimnames=list(.yrs, .colnames))

# Process the variables in order:

#   YEAR
phys3mo[ , 'YEAR'] <- .yrs

#   PDO
.names <- paste('PDO_', ma3Names, sep='')
.dat <- threeMoMA(PDO.mon)
phys3mo[ , .names] <- .dat

#   ONI
.names <- paste('ONI_', ma3Names, sep='')
.dat <- threeMoMA(ONI.mon)
phys3mo[ , .names] <- .dat

#   UWI
.names <- paste('UWI_', ma3Names, sep='')
.dat <- threeMoMA(UWI.mon)
phys3mo[ , .names] <- .dat

#   BFL
# .names <- paste('BFL_', ma3Names, sep='')
# .dat <- threeMoMA(BFL.mon)
# phys3mo[ , .names] <- .dat

#   SLH
# .names <- paste('SLH_', ma3Names, sep='')
# .dat <- threeMoMA(ASL.45N.mon)  #NOTE: data series name differs
# phys3mo[ , .names] <- .dat

#   SST
.names <- paste('SST_', ma3Names, sep='')
.dat <- threeMoMA(CWT.mon)  #NOTE: data series name differs
phys3mo[ , .names] <- .dat

#   NPI
# .names <- paste('NPI_', ma3Names, sep='')
# .dat <- threeMoMA(NPI.mon)
# phys3mo[ , .names] <- .dat

#   MEI - NOT 3mo MA!!
# MEI hass 12 2-mo MAs + 2 more variables:
#   MEI_ND.1 (which seems to be identical to MEI_ND), and
#   MEI_DJ.1 the average of Dec(Y) + Jan(Y+1)

# .names <- paste('MEI_', c('DJ', 'JF', 'FM', 'MA', 'AM', 'MJ',
#                           'JJ', 'JA', 'AS', 'SO', 'ON', 'ND',
#                           'ND.1', 'DJ.1'), sep='')
# ##print(.names)
# # compute the first 12 variables (as in threeMoMA above:
# .mtab <- matrix(NA, nrow=length(.yrs), ncol=12,
#                 dimnames=list(.yrs, month.abb))
# .mtab[.yrs %in% MEI.mon[ , 'Year'], ] <-
#     as.matrix(MEI.mon)[MEI.mon[ , 'Year'] %in% .yrs, 2:13]
# # MEI has no internal missing values, so don't need to worry about them,
# # so MA is just ave. of data and data lagged -1 month
# .dat <- 0.5 * (.mtab + cbind(c(NA, .mtab[1:(.nyrs-1), 12]), .mtab[ , 1:11]))
# # bind on the two odd variables at the end:
# .dat <- cbind(.dat, .dat[ , 12],
#               0.5 * (.mtab[ , 12] + c(.mtab[2:.nyrs, 1], NA)))
# phys3mo[ , .names] <- .dat

#   NPGO
.names <- paste('NPGO_', ma3Names, sep='')
.dat <- threeMoMA(NPGO.mon)
phys3mo[ , .names] <- .dat

#  SPR.TRN - Annual Series
print(summary(SPT.LGR.ann))
phys3mo[.yrs %in% SPT.LGR.ann$DecYr , 'SPR.TRN'] <-
  SPT.LGR.ann$Data[SPT.LGR.ann$DecYr %in% .yrs]

write.table(phys3mo, file.path(d.dir, 'Physical_3mo.dat'),
            sep='\t', row.names=FALSE)
